"""
판매(Sales) 도메인 테이블 스키마 정의.
`ERP_Schema_v2_Corrected` 워크북의 Column Dictionary를 기준으로 생성했다.
담당: 판매(rag_sales) 도메인. 다른 도메인 테이블은 정의하지 않는다.
"""

# 적재 순서 (FK 의존성에 따른 topological order)
TABLE_LOAD_ORDER = [
    "customers",
    "price_lists",
    "credit_limits",
    "customer_contracts",
    "sales_quotes",
    "discounts",
    "sales_quote_lines",
    "sales_orders",
    "sales_order_lines",
    "order_fulfillment",
    "fulfillment_lines",
    "invoices",
    "sales_reports",
    "sales_forecasts",
]

# 엑셀 시트명 -> MySQL 테이블명 매핑
SHEET_TO_TABLE = {
    "Customers": "customers",
    "Price Lists": "price_lists",
    "Credit Limits": "credit_limits",
    "Customer Contracts": "customer_contracts",
    "Sales Quotes": "sales_quotes",
    "Discounts": "discounts",
    "Sales Quote Lines": "sales_quote_lines",
    "Sales Orders": "sales_orders",
    "Sales Order Lines": "sales_order_lines",
    "Order Fulfillment": "order_fulfillment",
    "Fulfillment Lines": "fulfillment_lines",
    "Invoices": "invoices",
    "Sales Reports": "sales_reports",
    "Sales Forecasts": "sales_forecasts",
}

# 테이블별 컬럼 정의: (컬럼명, MySQL 타입, PK 여부, FK 대상 테이블(sales 내부만) 또는 None)
SALES_SCHEMA = {
    "customers": {
        "source_sheet": "Customers",
        "columns": [
            {"name": "customer_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "customer_code", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "customer_name", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "customer_type", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "industry", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "contact_person", "type": "VARCHAR(100)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "email", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "phone_number", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "billing_address", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "shipping_address", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "country", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_id", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "payment_terms", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "account_manager_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "is_active", "type": "TINYINT(1)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "customer_id",
    },
    "price_lists": {
        "source_sheet": "Price Lists",
        "columns": [
            {"name": "price_list_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "item_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "list_code", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "list_name", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "effective_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "expiry_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "customer_segment", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "is_active", "type": "TINYINT(1)", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "price_list_id",
    },
    "credit_limits": {
        "source_sheet": "Credit Limits",
        "columns": [
            {"name": "credit_limit_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "credit_limit_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "current_exposure", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "available_credit", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "credit_rating", "type": "VARCHAR(10)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "review_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "approved_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "is_on_hold", "type": "TINYINT(1)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "credit_limit_id",
    },
    "customer_contracts": {
        "source_sheet": "Customer Contracts",
        "columns": [
            {"name": "customer_contract_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "contract_number", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "contract_name", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "start_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "end_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "total_value", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "payment_terms", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "auto_renew", "type": "TINYINT(1)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "document_url", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "status", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "customer_contract_id",
    },
    "sales_quotes": {
        "source_sheet": "Sales Quotes",
        "columns": [
            {"name": "sales_quote_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "quote_number", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quote_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "valid_until", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "sales_rep_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "subtotal", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "total_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "notes", "type": "TEXT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "status", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_quote_id",
    },
    "discounts": {
        "source_sheet": "Discounts",
        "columns": [
            {"name": "discount_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "price_list_id", "type": "BIGINT", "is_pk": False, "fk_table": 'price_lists', "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "discount_code", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_name", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_type", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_value", "type": "DECIMAL(10,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "min_order_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "max_discount_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "valid_from", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "valid_to", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "applicable_to", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "is_active", "type": "TINYINT(1)", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "discount_id",
    },
    "sales_quote_lines": {
        "source_sheet": "Sales Quote Lines",
        "columns": [
            {"name": "sales_quote_line_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": False},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "sales_quote_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_quotes', "nullable": False},
            {"name": "line_number", "type": "INT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "item_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "description", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "uom_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quantity", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "unit_price", "type": "DECIMAL(18,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_percent", "type": "DECIMAL(5,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_code_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "line_total", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_quote_line_id",
    },
    "sales_orders": {
        "source_sheet": "Sales Orders",
        "columns": [
            {"name": "sales_order_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "quote_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_quotes', "nullable": True},
            {"name": "order_number", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "order_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "required_delivery_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "delivery_address", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "sales_rep_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "subtotal", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "total_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "payment_terms", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "status", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "approval_request_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_order_id",
    },
    "sales_order_lines": {
        "source_sheet": "Sales Order Lines",
        "columns": [
            {"name": "sales_order_line_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": False},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "sales_order_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_orders', "nullable": False},
            {"name": "line_number", "type": "INT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "item_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "description", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "uom_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quantity", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "unit_price", "type": "DECIMAL(18,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_percent", "type": "DECIMAL(5,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_code_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "line_total", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quantity_delivered", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "warehouse_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_order_line_id",
    },
    "order_fulfillment": {
        "source_sheet": "Order Fulfillment",
        "columns": [
            {"name": "fulfillment_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "order_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_orders', "nullable": True},
            {"name": "shipment_number", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "shipment_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "carrier", "type": "VARCHAR(100)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tracking_number", "type": "VARCHAR(100)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "delivery_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "packed_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "shipped_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "status", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "notes", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "fulfillment_id",
    },
    "fulfillment_lines": {
        "source_sheet": "Fulfillment Lines",
        "columns": [
            {"name": "fulfillment_line_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": False},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "fulfillment_id", "type": "BIGINT", "is_pk": False, "fk_table": 'order_fulfillment', "nullable": False},
            {"name": "sales_order_line_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_order_lines', "nullable": True},
            {"name": "line_number", "type": "INT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "item_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "description", "type": "VARCHAR(255)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "uom_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quantity", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "unit_price", "type": "DECIMAL(18,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "discount_percent", "type": "DECIMAL(5,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_code_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "line_total", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "quantity_shipped", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "warehouse_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "fulfillment_line_id",
    },
    "invoices": {
        "source_sheet": "Invoices",
        "columns": [
            {"name": "invoice_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "fulfillment_id", "type": "BIGINT", "is_pk": False, "fk_table": 'order_fulfillment', "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "order_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_orders', "nullable": True},
            {"name": "invoice_number", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "invoice_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "due_date", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "subtotal", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "tax_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "total_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "amount_paid", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "outstanding_amount", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "currency", "type": "VARCHAR(5)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "payment_terms", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "status", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "customer_invoice_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "invoice_id",
    },
    "sales_reports": {
        "source_sheet": "Sales Reports",
        "columns": [
            {"name": "sales_report_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "sales_order_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_orders', "nullable": True},
            {"name": "invoice_id", "type": "BIGINT", "is_pk": False, "fk_table": 'invoices', "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "report_code", "type": "VARCHAR(20)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "report_name", "type": "VARCHAR(150)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "report_type", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "period_start", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "period_end", "type": "DATE", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "total_revenue", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "orders_count", "type": "INT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "generated_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "generated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_report_id",
    },
    "sales_forecasts": {
        "source_sheet": "Sales Forecasts",
        "columns": [
            {"name": "sales_forecast_id", "type": "BIGINT", "is_pk": True, "fk_table": None, "nullable": True},
            {"name": "company_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": False},
            {"name": "sales_report_id", "type": "BIGINT", "is_pk": False, "fk_table": 'sales_reports', "nullable": True},
            {"name": "item_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "customer_id", "type": "BIGINT", "is_pk": False, "fk_table": 'customers', "nullable": True},
            {"name": "product_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "forecast_period", "type": "VARCHAR(30)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "forecasted_quantity", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "forecasted_revenue", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "actual_quantity", "type": "DECIMAL(14,4)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "actual_revenue", "type": "DECIMAL(18,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "forecast_method", "type": "VARCHAR(50)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "accuracy_percent", "type": "DECIMAL(6,2)", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_by_user_id", "type": "BIGINT", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "created_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "is_pk": False, "fk_table": None, "nullable": True},
        ],
        "pk": "sales_forecast_id",
    },
}